
// export { Layout as default } from '@/components/Layout'

import './globals.css'
import { Inter } from 'next/font/google'
import clsx from 'clsx'

import '@/styles/tailwind.css'

const inter = Inter({ subsets: ['latin'], display: 'swap',
variable: '--font-inter', })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" 
    className={clsx('h-full bg-gray-50 antialiased ', inter.variable)}>
      <body className={inter.className}> <div className="flex min-h-full flex-col ">{children}</div></body>
    </html>
  )
}
